openapi: 3.0.0
info:
  title: PipeDreamTest-HIBP
  version: 1.0.0
servers:
- url: https://eobo1ufqdmmqq5b.m.pipedream.net/api/v3
paths:
  /breachedaccount/{email}:
    get:
      tags:
      - default
      parameters:
      - in: path
        name: email
        schema:
          type: string
        required: true
      - in: header
        name: User-Agent
        schema:
          type: string
        required: true
      # - in: query
      #   name: AllPreviousPromptsFullMessage
      #   schema:
      #     type: string
      #   required: true
      # - in: query
      #   name: AllCurrentSessionVariables
      #   schema:
      #     type: string
      #   required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
        '401':
          description: Unauthorized
          content:
            application/json: {}
        default:
          description: default
      summary: Get list of breaches for an account
components: {}
