openapi: 3.0.0
info:
  title: HIBP-Collection
  version: 1.0.0
servers:
- url: https://haveibeenpwned.com
paths:
  /api/v3/breachedaccount/{email}:
    get:
      tags:
      - default
      summary: HIBP-Request
      parameters:
      - in: path
        name: email
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
        '404':
          description: Not found
          content:
            application/json: {}
        '401':
          description: Unauthorized
          content:
            application/json: {}
        default:
          description: Unexpected error
          schema: {}
          content:
            application/json: {}
components: {}
