openapi: 3.0.0
info:
  title: HIBP-Collection
  version: 1.0.0
servers:
- url: https://haveibeenpwned.com
basePath: /api/v3
paths:
  /breachedaccount/{email}:
    get:
      tags:
      - default
      summary: HIBP-Request
      parameters:
      - name: email
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
        '404':
          description: Not found
          content:
            application/json: {}
        '401':
          description: Unauthorized
          content:
            application/json: {}
components: {}
