openapi: 3.0.0
info:
  title: HIBP-Collection
  version: 1.0.0
basePath: /api/v3
host: haveibeenpwned.com
servers:
- url: https://haveibeenpwned.com/api/v3
paths:
  /breachedaccount/{email}:
    get:
      tags:
      - default
      parameters:
      - in: path
        name: email
        schema:
          type: string
        required: true
        description: The email of the user.
      responses:
        '200':
          description: Successful response
          schema: {}
        '400':
          description: Bad request
          schema: {}
        '401':
          description: Unauthorized
          schema: {}
        '403':
          description: Forbidden
          schema: {}
        '404':
          description: Not found
          schema: {}
        '429':
          description: Too many requests
          schema: {}
        '503':
          description: Service unavailable
          schema: {}
      summary: Get list of breaches for an account
components: {}
schemes:
- 'https:'