openapi: 3.0.0
info:
  title: HIBP-Collection
  version: 1.0.0
servers:
- url: https://haveibeenpwned.com
basePath: /api/v3
paths:
  "/breachedaccount/{account}":
    get:
      tags:
      - default
      summary: HIBP-Request
      parameters:
      - name: account
        in: path
        schema:
          type: string
        required: true
        default: 'go2mdebac@gmail.com'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
        '404':
          description: Not found
          content:
            application/json: {}
        '403':
          description: Forbidden
          content:
            application/json: {}
components: {}
