openapi: 3.0.0
info:
  title: HIBP-Collection
  version: 1.0.0
servers:
- url: https://haveibeenpwned.com
basePath: /api/v3
paths:
  breachedaccount/{email}:
    get:
      tags:
      - default
      parameters:
      - in: path
        name: email
        schema:
          type: string
        required: true
        description: The email of the user.
      responses:
        default:
          description: default
          schema: {}
      summary: Get list of breaches for an account
components: {}
