---
openapi: 3.0.0
info:
  title: HIBP-Collection
  version: 1.0.0
servers:
- url: https://haveibeenpwned.com
paths:
  "/api/v3/breachedaccount/{account}":
    get:
      tags:
      - default
      summary: HIBP-Request
      parameters:
      - name: account
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
components: {}
