openapi: 3.0.0
info:
  title: HIBP-Collection
  version: 1.0.0
servers:
  - url: https://haveibeenpwned.com/api/v3
#components:
#  securitySchemes:
#    api_key:
#      type: apiKey
#      in: header
#      name: hibp-api-key
paths:
  /breachedaccount/{email}:
    get:
      tags:
        - default
      parameters:
        - in: path
          name: email
          schema:
            type: string
          example: philipb@appsol.co.nz
          required: true
        - in: header
          name: hibp-api-key
          schema:
            type: string
      responses:
        default:
          description: default
 #     security:
 #       - api_key: []
      summary: Get list of breaches for an account