openapi: 3.0.0
info:
  title: HIBP-Collection
  version: 1.0.0
servers:
  - url: https://haveibeenpwned.com/api/v3
paths:
  /breachedaccount/{email}:
    get:
      tags:
      - default
      parameters:
      - in: path
        name: email
        schema:
          type: string
        required: true
        description: The email of the user.
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
        '400':
          description: Bad request
          content:
            application/json: {}
        '401':
          description: Unauthorized
          content:
            application/json: {}
        '403':
          description: Forbidden
          content:
            application/json: {}
        '404':
          description: Not found
          content:
            application/json: {}
        '429':
          description: Too many requests
          content:
            application/json: {}
        '503':
          description: Service unavailable
          content:
            application/json: {}
        default:
          description: Unexpected error
          content:
            application/json: {}
      summary: Get list of breaches for an account
components: {}